@include('livewire.global.search-and-filters.secondary-search', [
    'inputXFilterString' => 'inputDosenFilter',
    'xSearchResultsString' => 'dosenSearchResults',
    'iconString' => 'user',
    'placeholderString' => 'Filter berdasarkan Dosen...',
    'xSearchQueryString' => 'dosenSearchQuery',
    'selectedXId' => $selectedDosenId,
    'selectedXName' => $dosen_name,
    'resetXFilter' => 'resetDosenFilter()',
    'xSearchQuery' => $dosenSearchQuery,
    'xSearchResults' => $dosenSearchResults,
    'selectXForFilterString' => 'selectDosenForFilter',
    'typeXString' => 'name',
    'typeX2String' => 'nip_full',
    'typeX3String' => 'status',
    'typeKodeString' => 'kode_pr',
    'unfoundString' => 'Tidak ada Dosen ditemukan!',
])
